import { useEffect, useState, type FormEvent } from 'react';
import { Check, MessageSquare, Sparkles, Star } from 'lucide-react';
import { api } from './client';

type Site = { id: string; name: string };
type Annotation = { note: string; tags: string[]; favorite: boolean };
type Event = { id: string; siteId: string; siteName: string; pageId?: string; versionId?: string; kind: string; message: string; createdAt: string; url?: string; readAt?: string };
type SavedVersion = Annotation & { id: string; pageId: string; siteName: string; title: string; url: string; capturedAt: string };
const date = (value: string) => new Date(value).toLocaleString('it-IT');
const day = (ago = 0) => { const d = new Date(); d.setDate(d.getDate() - ago); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; };
const queryDate = (value: string, end = false) => value ? new Date(value + (end ? 'T23:59:59.999' : 'T00:00:00')).toISOString() : '';
const put = <T,>(path: string, body: unknown) => api<T>(path, { method: 'PUT', body: JSON.stringify(body) });
const versionLink = (page: string, version?: string) => `#/page/${page}${version ? '/' + version : ''}`;
function ErrorBox({ message }: { message: string }) { return message ? <div className="notice error" role="alert">{message}</div> : null; }
function Dates({ from, to, setFrom, setTo }: { from: string; to: string; setFrom: (s: string) => void; setTo: (s: string) => void }) {
  return <><label>Dal<input type="date" value={from} onChange={e => setFrom(e.target.value)} /></label><label>Al<input type="date" value={to} onChange={e => setTo(e.target.value)} /></label></>;
}
function Pages({ offset, total, size, set }: { offset: number; total: number; size: number; set: (n: number) => void }) {
  return <div className="list-pagination"><span>{total ? `${offset + 1}–${Math.min(offset + size, total)} di ${total}` : 'Nessun risultato'}</span><button className="button secondary compact" disabled={!offset} onClick={() => set(Math.max(0,offset-size))}>Precedenti</button><button className="button secondary compact" disabled={offset+size >= total} onClick={() => set(offset+size)}>Successivi</button></div>;
}
export function VersionAnnotation({ versionId, capturedAt }: { versionId: string; capturedAt: string }) {
  const [value, setValue] = useState<Annotation | null>(null), [tags, setTags] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false), [saved, setSaved] = useState(false);
  useEffect(() => { let cancelled = false; api<Annotation>(`/api/versions/${versionId}/annotation`).then(v => { if (!cancelled) { setValue(v); setTags(v.tags.join(', ')); } }).catch(e => { if (!cancelled) setError(e.message); }); return () => { cancelled = true; }; }, [versionId]);
  async function save(event: FormEvent) {
    event.preventDefault(); setBusy(true); setError(''); setSaved(false);
    try { await put(`/api/versions/${versionId}/annotation`, { ...value, tags: tags.split(',').map(s => s.trim()).filter(Boolean) }); setSaved(true); }
    catch (error) { setError((error as Error).message); } finally { setBusy(false); }
  }
  return <section className="panel annotation-panel"><div className="panel-heading"><div><h2><MessageSquare size={18} /> Appunti su questa versione</h2><p>Copia del {capturedAt}. Gli appunti riguardano solo questa acquisizione.</p></div><a className="text-button" href="#/library">Apri raccolta</a></div><ErrorBox message={error} />{value && <form onSubmit={save}><fieldset disabled={busy} onChange={() => setSaved(false)}><label className="checkbox-label"><input type="checkbox" checked={value.favorite} onChange={e => setValue({ ...value, favorite: e.target.checked })} /><span><Star size={16} /> Preferita</span></label><label>Tag<input aria-label="Tag" value={tags} maxLength={500} placeholder="webinar, lead magnet, lancio" onChange={e => setTags(e.target.value)} /><small>Separa con virgole, fino a 12 tag.</small></label><label>Annotazione<textarea rows={4} maxLength={20000} value={value.note} onChange={e => setValue({ ...value, note: e.target.value })} placeholder="Cosa stanno testando? Quale offerta è cambiata?" /></label></fieldset><button className="button primary" disabled={busy}>{busy ? 'Salvataggio…' : 'Salva appunti'}</button>{saved && <span className="saved-message" role="status"><Check size={16} /> Appunti salvati nella raccolta</span>}</form>}</section>;
}
export function InboxView({ sites }: { sites: Site[] }) {
  const [from, setFrom] = useState(day(6)), [to, setTo] = useState(day()), [site, setSite] = useState(''), [group, setGroup] = useState('competitor');
  const [unread, setUnread] = useState(true), [important, setImportant] = useState(true), [offset, setOffset] = useState(0), [revision, setRevision] = useState(0);
  const [preferences, setPreferences] = useState<{ kinds: string[]; available: Record<string,string> } | null>(null), [data, setData] = useState<{ total: number; unread: number; events: Event[] } | null>(null), [error, setError] = useState(''), [busy, setBusy] = useState(false), [loading, setLoading] = useState(true), [notice, setNotice] = useState('');
  useEffect(() => { api<NonNullable<typeof preferences>>('/api/inbox/preferences').then(setPreferences).catch(e => setError(e.message)); }, []);
  useEffect(() => { setOffset(0); }, [from,to,site,group,unread,important]);
  useEffect(() => {
    let cancelled = false; setLoading(true); setError('');
    const query = new URLSearchParams({ from:queryDate(from),to:queryDate(to,true),site,group,unread: String(unread),important: String(important),offset: String(offset) });
    api<NonNullable<typeof data>>('/api/inbox?' + query).then(d => { if (!cancelled) { setData(d); setLoading(false); } }).catch(e => { if (!cancelled) { setError(e.message); setLoading(false); } });
    return () => { cancelled = true; };
  }, [from,to,site,group,unread,important,offset,revision]);
  useEffect(() => { const timer = setInterval(() => { if (!document.hidden) setRevision(v => v+1); },30000); return () => clearInterval(timer); }, []);
  async function mark(events: Event[], read: boolean) { setBusy(true); setError(''); try { await put('/api/inbox/read', { ids: events.map(e => e.id), read }); setRevision(v => v+1); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  const grouped = new Map<string, Event[]>();
  for (const event of data?.events || []) grouped.set(event.siteId, [...(grouped.get(event.siteId) || []),event]);
  return <><div className="page-heading"><div><span className="eyebrow">IL PUNTO SUI SITI CHE SEGUI</span><h1>Novità da leggere</h1><p>Un riepilogo degli eventi registrati, con i collegamenti alle copie archiviate.</p></div><button className="button secondary" disabled={loading || busy} onClick={() => setRevision(v => v+1)}>Aggiorna</button></div>
    <div className="panel library-filters"><label>Siti<select value={group} onChange={e => setGroup(e.target.value)}><option value="competitor">Competitor</option><option value="own">I miei siti</option><option value="all">Tutti</option></select></label><label>Singolo sito<select value={site} onChange={e => { setSite(e.target.value); setGroup('all'); }}><option value="">Tutti i siti</option>{sites.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label><Dates {...{ from,to,setFrom,setTo }} /><button className="text-button" onClick={() => { setFrom(day(6)); setTo(day()); }}>Ultimi 7 giorni</button><label className="checkbox-label"><input type="checkbox" checked={unread} onChange={e => setUnread(e.target.checked)} /><span>Solo da leggere</span></label><label className="checkbox-label"><input type="checkbox" checked={important} onChange={e => setImportant(e.target.checked)} /><span>Solo tipi selezionati</span></label></div>
    {preferences && <details className="panel inbox-preferences"><summary>Quali novità vuoi seguire?</summary><div className="event-kind-options">{Object.entries(preferences.available).map(([kind,label]) => <label className="checkbox-label" key={kind}><input type="checkbox" checked={preferences.kinds.includes(kind)} onChange={e => { setNotice(''); setPreferences({ ...preferences, kinds: e.target.checked ? [...preferences.kinds,kind] : preferences.kinds.filter(v => v!==kind) }); }} /><span>{label}</span></label>)}</div><p>Le preferenze filtrano questo riepilogo. Lo storico completo resta conservato. Nessun messaggio viene inviato a servizi esterni.</p><button className="button secondary" disabled={busy} onClick={async () => { setBusy(true); setError(''); try { await put('/api/inbox/preferences', { kinds: preferences.kinds }); setRevision(v => v+1); setNotice('Preferenze salvate'); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }}>Salva preferenze</button>{notice && <span className="saved-message" role="status">{notice}</span>}</details>}
    <ErrorBox message={error} /><div className="list-toolbar"><strong>{data?.unread || 0} da leggere nei filtri scelti</strong><button className="button secondary compact" disabled={busy || loading || !data?.events.length} onClick={() => mark(data!.events,true)}>Segna questi eventi come letti</button></div>
    <div aria-busy={loading}>{!data?.events.length && !loading && <div className="panel library-empty"><Sparkles size={26} /><h2>Nessuna novità con questi filtri</h2><p>Amplia il periodo o includi gli eventi già letti.</p></div>}{[...grouped].map(([siteId,events]) => <section className="panel digest-site" key={siteId}><div className="panel-heading"><h2><a href={`#/site/${siteId}`}>{events[0].siteName}</a></h2><span>{events.length} eventi in questa pagina</span></div>{events.map(e => <article key={e.id} className={`digest-event ${e.readAt ? 'is-read' : ''}`}><div><time>{date(e.createdAt)}</time><span className="badge">{e.readAt ? 'Letto' : 'Da leggere'}</span><h3>{e.message}</h3><p>{e.url}</p><div className="button-group">{e.pageId && <a className="text-button" href={versionLink(e.pageId,e.versionId)}>{e.versionId ? 'Apri questa versione' : 'Apri storico pagina'}</a>}<button className="text-button" disabled={busy || loading} onClick={() => mark([e],!e.readAt)}>{e.readAt ? 'Segna da leggere' : 'Segna come letto'}</button></div></div></article>)}</section>)}</div><Pages offset={offset} total={data?.total || 0} size={200} set={setOffset} /></>;
}
export function LibraryView({ sites }: { sites: Site[] }) {
  const [from,setFrom] = useState(''), [to,setTo] = useState(''), [site,setSite] = useState(''), [tag,setTag] = useState(''), [q,setQ] = useState(''), [favorite,setFavorite] = useState(false), [offset,setOffset] = useState(0);
  const [data,setData] = useState<{ total: number; tags: string[]; versions: SavedVersion[] } | null>(null), [error,setError] = useState(''), [loading,setLoading] = useState(false);
  useEffect(() => { setOffset(0); }, [from,to,site,tag,q,favorite]);
  useEffect(() => {
    let cancelled = false; setLoading(true);
    const timer = setTimeout(() => { api<NonNullable<typeof data>>('/api/library?' + new URLSearchParams({ from:queryDate(from),to:queryDate(to,true),site,tag,q,favorite:String(favorite),offset:String(offset) })).then(d => { if (!cancelled) { setData(d); setError(''); setLoading(false); } }).catch(e => { if (!cancelled) { setError(e.message); setLoading(false); } }); },200);
    return () => { cancelled = true; clearTimeout(timer); };
  }, [from,to,site,tag,q,favorite,offset]);
  return <><div className="page-heading"><div><span className="eyebrow">RITROVA QUELLO CHE CONTA</span><h1>Raccolta</h1><p>Le versioni con appunti, tag o preferiti, raccolte da tutti i tuoi siti.</p></div></div><div className="panel library-filters"><label>Cerca negli appunti<input type="search" value={q} maxLength={200} placeholder="Titolo, indirizzo, tag o annotazione" onChange={e => setQ(e.target.value)} /></label><label>Sito<select value={site} onChange={e => setSite(e.target.value)}><option value="">Tutti i siti</option>{sites.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Tag<input list="saved-tags" value={tag} maxLength={40} placeholder="Tutti i tag" onChange={e => setTag(e.target.value)} /><datalist id="saved-tags">{data?.tags.map(t => <option key={t} value={t} />)}</datalist></label><Dates {...{ from,to,setFrom,setTo }} /><label className="checkbox-label"><input type="checkbox" checked={favorite} onChange={e => setFavorite(e.target.checked)} /><span>Solo preferite</span></label></div><ErrorBox message={error} /><div className="saved-versions" aria-busy={loading}>{data?.versions.map(v => <article className="panel saved-version" key={v.id}><div className="saved-version-heading"><span>{v.siteName}</span>{v.favorite && <Star size={18} aria-label="Preferita" />}</div><h2><a href={versionLink(v.pageId,v.id)}>{v.title || v.url}</a></h2><time>{date(v.capturedAt)}</time><p className="saved-url">{v.url}</p><div className="saved-tags">{v.tags.map(t => <button key={t} className="badge" onClick={() => setTag(t)}>{t}</button>)}</div>{v.note && <p className="saved-note">{v.note}</p>}<a className="text-button" href={versionLink(v.pageId,v.id)}>Apri versione e appunti</a></article>)}</div>{!loading && !data?.versions.length && <div className="panel library-empty"><Star size={26} /><h2>Nessuna versione nella raccolta</h2><p>Apri una pagina e aggiungi appunti, tag o un preferito alla versione che ti interessa.</p></div>}<Pages offset={offset} total={data?.total || 0} size={100} set={setOffset} /></>;
}
